image: golang:1.25.4

stages:
  - build
  - test

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - mcphe

test:
  stage: test
  script:
    - make test

release:
  stage: release
  script:
    - make release
  artifacts:
    paths:
      - mcphe
  only:
    - tags