image: golang:1.25.4

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - mcphe

test:
  stage: test
  script:
    - make test
    # need to install npm and nodejs and tsc and npm test
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    - apt-get install -y nodejs
    - npm install -g typescript@5.8.3
    - cd plugin-devel && npm install
    - npm test

release:
  stage: release
  script:
    - make release
  artifacts:
    paths:
      - mcphe
  only:
    - tags