---
Version: "1.0"
port: "8000"
host: "0.0.0.0"
use_https: false
bearer_token: ""
tools:
  "ping": false
  "google_search": false
  "http_request_get": true
allowed_domains:
  - "crumpton.org"
  - "reddit.com"
  - "github.com"
  - "stackoverflow.com"
  - "medium.com"
  - "dev.to"
  - "news.ycombinator.com"
  - "gitlab.com"
verbosity_level: 4
