---
Version: "1.0.0"
port: "8001"
host: "127.0.0.1"
use_https: false
bearer_token: ""
token_secret: oludie3Aigae6Ohru6AhMigh
run_as_root: false
verbosity_level: 4
plugins:
  get_ip:
    allowed_domains: ["ifconfig.io"]
    allowed_http_methods:
      - "GET"
  get_datetime:
  google_search:
    google_api_key: "abc123"
    google_cx_id: "cx456"
    allowed_domains: ["google.com"]
  http_request_get:
    allowed_domains:
      - "reddit.com"
      - "github.com"
      - "stackoverflow.com"
      - "medium.com"
      - "dev.to"
      - "news.ycombinator.com"
      - "gitlab.com"
    allowed_env_vars: []
    api_token: "xyz"
  wikipedia_search:
    allowed_domains: ["en.wikipedia.org"]
  memory:
    enabled: true
    allowed_write_file_paths: ["/tmp/mcphe/"]
    allowed_read_file_paths: ["/tmp/mcphe/"]
    allowed_http_headers:
      - "mcp-request-id"
      - "mcp-session-id"
    options:
      data_dir: "/tmp/mcphe"
  gitlab:
    options:
      # gitlabApiKey: "glpat-using environment variable is more secure than hardcoding the API key in the config file. But you can."
      # prioritize ENV var over config file value if both are present
      gitlabApiKeyFromEnvVar: "GITLAB_API_KEY"
      gitlabBaseUrl: "https://gitlab.crumpton.org"
    allowed_domains: ["gitlab.com", "gitlab.crumpton.org", "ollama.crumpton.org"]
    allowed_env_vars: ["GITLAB_API_KEY"]
  zabbix:
    allowed_env_vars: ["ZABBIX_API_URL", "ZABBIX_USER", "ZABBIX_PASSWORD", "ZABBIX_AUTH_TOKEN"]
    allowed_domains: ["ollama.crumpton.org","zabbix.crumpton.org"]
  wikijs:
    allowed_env_vars: ["WIKIJS_API_URL", "WIKIJS_API_TOKEN"]
    allowed_domains: ["wiki.crumpton.org"]
  home_assistant:
    allowed_domains:
      - homeassistant.local # or IP address
    allowed_env_vars:
      - "HASS_URL"
      - "HASS_TOKEN"
    options:
      ApiUrl: "http://homeassistant.local:8123"
  gitea:
    allowed_env_vars: ["GITEA_API_KEY", "GITEA_API_URL"]
    allowed_domains: ["git.crumpton.org"]
  opensearch:
    allowed_env_vars: ["OPENSEARCH_BASE_URL", "OPENSEARCH_USERNAME", "OPENSEARCH_PASSWORD"]
    allowed_domains: ['opensearch.crumpton.org']
  kibana:
    allowed_env_vars: ["KIBANA_BASE_URL", "KIBANA_USERNAME", "KIBANA_PASSWORD"]
    allowed_domains: ['elk.crumpton.org']
  proxmox_api:
    allowed_env_vars: ["PROXMOX_BASE_URL", "PROXMOX_API_TOKEN"]
    allowed_domains: ['pve02.crumpton.org']
